### ISSUE TITLE
How to do reconciliation when client tick is lesser than latest server state tick?

### ISSUE THREAD

**Issue by TheMetaverseEngineer** [Ajackster/ClientPredictionTutorial#1]
Hello, thank u so much for this awesome repository. I've been struggling with concepts of client prediction and server reconciliation. so, do you know what we should do when client tick is lesser than latest server state tick? because when this is the case and we use our latest server state tick to get the buffer index, then we are comparing two different ticks, for example when the latest server state tick is 1024 and client's current tick is 1000 then the server state buffer index would be 0. at this index the client was in (x: 0, y: 0) for example but the server is in (x: 10, y:0) for example so there would be a huge position error, how could we prevent this?

**Comment by GamemodeSurvival** [comment]
I'm also having this issue, when moving its fine, but standing still it seems like it keeps trying to go back to a previous position and replay it, so the player goes up and down very fast
